// <copyright file="build-task-unit-tests.wren" company="Soup">
// Copyright (c) Soup. All rights reserved.
// </copyright>

import "soup-test" for SoupTest, SoupTestOperation
import "soup|csharp-compiler:./mock-compiler" for MockCompiler
import "soup|csharp-compiler:./build-options" for BuildOptimizationLevel, BuildTargetType
import "soup|csharp-compiler:./compile-options" for CompileOptions, NullableState
import "soup|csharp-compiler:./managed-compile-options" for LinkTarget
import "soup|build-utils:./path" for Path
import "../../extension/tasks/build-task" for BuildTask
import "../../test/assert" for Assert

class BuildTaskUnitTests {
	construct new() {
	}

	RunTests() {
		System.print("BuildTaskUnitTests.Build_Executable")
		this.Build_Executable()
		System.print("BuildTaskUnitTests.Build_Library_MultipleFiles")
		this.Build_Library_MultipleFiles()
	}

	// [Fact]
	Build_Executable() {
		// Setup the input build state
		SoupTest.initialize()
		var activeState = SoupTest.activeState
		var globalState = SoupTest.globalState

		// Setup dependencies table
		var dependenciesTable = {}
		globalState["Dependencies"] = dependenciesTable
		dependenciesTable["Tool"] = {
			"mwasplund|mkdir": {
				"SharedState": {
					"Build": {
						"RunExecutable": "/TARGET/mkdir.exe"
					}
				}
			}
		}

		// Setup build table
		var buildTable = {}
		activeState["Build"] = buildTable
		buildTable["Architecture"] = "x64"
		buildTable["Compiler"] = "MOCK"
		buildTable["TargetName"] = "my-program"
		buildTable["TargetVersion"] = "1.2.3"
		buildTable["TargetFramework"] = "net8.0"
		buildTable["TargetType"] = BuildTargetType.Executable
		buildTable["SourceRootDirectory"] = "C:/source/"
		buildTable["TargetRootDirectory"] = "C:/target/"
		buildTable["ObjectDirectory"] = "obj/"
		buildTable["BinaryDirectory"] = "bin/"
		buildTable["GenerateDirectory"] = "gen/"
		buildTable["Flavor"] = "Debug"
		buildTable["Source"] = [
			"TestFile.cs",
		]

		// Setup dotnet table
		var dotnetTable = {}
		activeState["DotNet"] = dotnetTable
		dotnetTable["ExecutablePath"] = "C:/bin/mock.dotnet.exe"

		// Register the mock compiler
		var compiler = MockCompiler.new()
		BuildTask.registerCompiler("MOCK", Fn.new { |activeState| compiler })

		BuildTask.evaluate()

		// Verify expected logs
		Assert.ListEqual(
			[
				"INFO: Using Compiler: MOCK",
				"INFO: Build Generate Done",
			],
			SoupTest.logs)

		var expectedCompileOptions = CompileOptions.new()
		expectedCompileOptions.OutputAssembly = Path.new("C:/target/bin/my-program.mock.dll")
		expectedCompileOptions.OutputRefAssembly = Path.new("C:/target/bin/ref/my-program.mock.dll")
		expectedCompileOptions.TargetType = LinkTarget.Executable
		expectedCompileOptions.SourceRootDirectory = Path.new("C:/source/")
		expectedCompileOptions.Sources = [
			Path.new("C:/source/TestFile.cs"),
			Path.new("C:/target/gen/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs"),
			Path.new("C:/target/gen/my-program.AssemblyInfo.cs"),
		]
		expectedCompileOptions.NullableState = NullableState.Enabled

		// Verify expected compiler calls
		Assert.ListEqual(
			[
				expectedCompileOptions,
			],
			compiler.GetCompileRequests())

		// Verify build state
		var expectedBuildOperations = [
			SoupTestOperation.new(
				"MakeDir [./obj/]",
				Path.new("/TARGET/mkdir.exe"),
				[
					"./obj/",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./obj/"),
				]),
			SoupTestOperation.new(
				"MakeDir [./bin/]",
				Path.new("/TARGET/mkdir.exe"),
				[
					"./bin/",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./bin/"),
				]),
			SoupTestOperation.new(
				"MakeDir [./gen/]",
				Path.new("/TARGET/mkdir.exe"),
				[
					"./gen/",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./gen/"),
				]),
			SoupTestOperation.new(
				"MakeDir [./bin/ref/]",
				Path.new("/TARGET/mkdir.exe"),
				[
					"./bin/ref/",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./bin/ref/"),
				]),
			SoupTestOperation.new(
				"WriteFile [./bin/my-program.runtimeconfig.json]",
				Path.new("./writefile.exe"),
				[
					"./bin/my-program.runtimeconfig.json",
					"{
  \"runtimeOptions\": {
    \"tfm\": \"net8.0\",
    \"framework\": {
      \"name\": \"Microsoft.NETCore.App\",
      \"version\": \"8.0.0\"
    },
    \"configProperties\": {
      \"System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization\": false
    }
  }
}",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./bin/my-program.runtimeconfig.json"),
				]),
			SoupTestOperation.new(
				"WriteFile [./gen/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs]",
				Path.new("./writefile.exe"),
				[
					"./gen/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",
					"// <autogenerated />
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute(\".NETCoreApp,Version=v8.0\", FrameworkDisplayName = \".NET 8.0\")]

",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./gen/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs"),
				]),
			SoupTestOperation.new(
				"WriteFile [./gen/my-program.AssemblyInfo.cs]",
				Path.new("./writefile.exe"),
				[
					"./gen/my-program.AssemblyInfo.cs",
					"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute(\"my-program\")]
[assembly: System.Reflection.AssemblyConfigurationAttribute(\"Debug\")]
[assembly: System.Reflection.AssemblyFileVersionAttribute(\"1.2.3\")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute(\"1.2.3+8513519b4c322896f461ecdcdb42594a66d6889a\")]
[assembly: System.Reflection.AssemblyProductAttribute(\"my-program\")]
[assembly: System.Reflection.AssemblyTitleAttribute(\"my-program\")]
[assembly: System.Reflection.AssemblyVersionAttribute(\"1.2.3\")]

// Generated by the MSBuild WriteCodeFragment class.

",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./gen/my-program.AssemblyInfo.cs"),
				]),
			SoupTestOperation.new(
				"MockCompile: 1",
				Path.new("MockCompiler.exe"),
				[
					"Arguments",
				],
				Path.new("MockWorkingDirectory"),
				[
					Path.new("./InputFile.in"),
				],
				[
					Path.new("./OutputFile.out"),
				]),
		]

		Assert.ListEqual(
			expectedBuildOperations,
			SoupTest.operations)
	}

	// [Fact]
	Build_Library_MultipleFiles() {
		// Setup the input build state
		SoupTest.initialize()
		var activeState = SoupTest.activeState
		var globalState = SoupTest.globalState

		// Setup dependencies table
		var dependenciesTable = {}
		globalState["Dependencies"] = dependenciesTable
		dependenciesTable["Tool"] = {
			"mwasplund|mkdir": {
				"SharedState": {
					"Build": {
						"RunExecutable": "/TARGET/mkdir.exe"
					}
				}
			}
		}

		// Setup build table
		var buildTable = {}
		activeState["Build"] = buildTable
		buildTable["Architecture"] = "x64"
		buildTable["Compiler"] = "MOCK"
		buildTable["TargetName"] = "my-library"
		buildTable["TargetVersion"] = "1.2.3"
		buildTable["TargetFramework"] = "net8.0"
		buildTable["TargetType"] = BuildTargetType.Library
		buildTable["SourceRootDirectory"] = "C:/source/"
		buildTable["TargetRootDirectory"] = "C:/target/"
		buildTable["ObjectDirectory"] = "obj/"
		buildTable["BinaryDirectory"] = "bin/"
		buildTable["GenerateDirectory"] = "gen/"
		buildTable["Flavor"] = "Debug"
		buildTable["Source"] = [
			"TestFile1.cpp",
			"TestFile2.cpp",
			"TestFile3.cpp",
		]
		buildTable["IncludeDirectories"] = [
			"Folder",
			"AnotherFolder/Sub",
		]
		buildTable["ModuleDependencies"] = [
			"../Other/bin/OtherModule1.mock.bmi",
			"../OtherModule2.mock.bmi",
		]
		buildTable["OptimizationLevel"] = BuildOptimizationLevel.None

		// Setup dotnet table
		var dotnetTable = {}
		activeState["DotNet"] = dotnetTable
		dotnetTable["ExecutablePath"] = "C:/bin/mock.dotnet.exe"

		// Register the mock compiler
		var compiler = MockCompiler.new()
		BuildTask.registerCompiler("MOCK", Fn.new { |activeState| compiler })

		BuildTask.evaluate()

		// Verify expected logs
		Assert.ListEqual(
			[
				"INFO: Using Compiler: MOCK",
				"INFO: Build Generate Done",
			],
			SoupTest.logs)

		// Setup the shared arguments
		var expectedCompileOptions = CompileOptions.new()
		expectedCompileOptions.OutputAssembly = Path.new("C:/target/bin/my-library.mock.dll")
		expectedCompileOptions.OutputRefAssembly = Path.new("C:/target/bin/ref/my-library.mock.dll")
		expectedCompileOptions.TargetType = LinkTarget.Library
		expectedCompileOptions.SourceRootDirectory = Path.new("C:/source/")
		expectedCompileOptions.Sources = [
			Path.new("C:/source/TestFile1.cpp"),
			Path.new("C:/source/TestFile2.cpp"),
			Path.new("C:/source/TestFile3.cpp"),
			Path.new("C:/target/gen/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs"),
			Path.new("C:/target/gen/my-library.AssemblyInfo.cs"),
		]
		expectedCompileOptions.NullableState = NullableState.Enabled

		// Verify expected compiler calls
		Assert.ListEqual(
			[
				expectedCompileOptions,
			],
			compiler.GetCompileRequests())

		// Verify build state
		var expectedBuildOperations = [
			SoupTestOperation.new(
				"MakeDir [./obj/]",
				Path.new("/TARGET/mkdir.exe"),
				[
					"./obj/",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./obj/"),
				]),
			SoupTestOperation.new(
				"MakeDir [./bin/]",
				Path.new("/TARGET/mkdir.exe"),
				[
					"./bin/",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./bin/"),
				]),
			SoupTestOperation.new(
				"MakeDir [./gen/]",
				Path.new("/TARGET/mkdir.exe"),
				[
					"./gen/",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./gen/"),
				]),
			SoupTestOperation.new(
				"MakeDir [./bin/ref/]",
				Path.new("/TARGET/mkdir.exe"),
				[
					"./bin/ref/",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./bin/ref/"),
				]),
			SoupTestOperation.new(
				"WriteFile [./gen/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs]",
				Path.new("./writefile.exe"),
				[
					"./gen/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",
					"// <autogenerated />
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute(\".NETCoreApp,Version=v8.0\", FrameworkDisplayName = \".NET 8.0\")]

",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./gen/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs"),
				]),
			SoupTestOperation.new(
				"WriteFile [./gen/my-library.AssemblyInfo.cs]",
				Path.new("./writefile.exe"),
				[
					"./gen/my-library.AssemblyInfo.cs",
					"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute(\"my-library\")]
[assembly: System.Reflection.AssemblyConfigurationAttribute(\"Debug\")]
[assembly: System.Reflection.AssemblyFileVersionAttribute(\"1.2.3\")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute(\"1.2.3+8513519b4c322896f461ecdcdb42594a66d6889a\")]
[assembly: System.Reflection.AssemblyProductAttribute(\"my-library\")]
[assembly: System.Reflection.AssemblyTitleAttribute(\"my-library\")]
[assembly: System.Reflection.AssemblyVersionAttribute(\"1.2.3\")]

// Generated by the MSBuild WriteCodeFragment class.

",
				],
				Path.new("C:/target/"),
				[],
				[
					Path.new("./gen/my-library.AssemblyInfo.cs"),
				]),
			SoupTestOperation.new(
				"MockCompile: 1",
				Path.new("MockCompiler.exe"),
				[
					"Arguments",
				],
				Path.new("MockWorkingDirectory"),
				[
					Path.new("./InputFile.in"),
				],
				[
					Path.new("./OutputFile.out"),
				]),
		]

		Assert.ListEqual(
			expectedBuildOperations,
			SoupTest.operations)
	}
}
